import { describe, expect, test } from "bun:test"
import solve from "."

const exampleInput = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`

describe("Day 7", () => {
    test("part A - full example", async () => {
        const result = await solve(exampleInput)
        expect(result.partA).toBe(21)
    })

    test("part B - full example", async () => {
        const result = await solve(exampleInput)
        expect(result.partB).toBe(40)
    })
})
